### PR TITLE
[CH1266][CH2041] Use Pinata Cloud for IPFS endpoint and pass in Auth Custom Headers

### PR DESCRIPTION
**Pull request by urbinaalex17**
[ch1266] Story details: https://app.clubhouse.io/masterventures/story/1266
[ch2041] Story details: https://app.clubhouse.io/masterventures/story/2041

We have two ways of connecting to the Pinata API:

1. Bearer Authentication
The token can be used as an Authorization header for all your API requests in the following format:
```javascript
"Authorization": "Bearer YOUR_JWT"
```
For this, we will need another ENV Vars, like `NEXT_PUBLIC_IPFS_JWT`

2. Custom Headers
If not using bearer authentication, the API requests will need to include two headers:

```javascript
pinata_api_key: (put the personal pinata api key here)
pinata_secret_api_key: (put the personal pinata secret api key here)
```
Here's a code snippet using axios

```javascript
const axios = require('axios');

export const testAuthentication = () => {
    const url = `https://api.pinata.cloud/data/testAuthentication`;
    return axios
        .get(url, {
            headers: {
                pinata_api_key: 'your pinata api key',
                pinata_secret_api_key: 'your pinata secret api key'
            }
        })
        .then(function (response) {
            //handle your response here
        })
        .catch(function (error) {
            //handle error here
        });
};
```

For this, we will need another ENV Vars, like `NEXT_PUBLIC_IPFS_API_KEY` and `NEXT_PUBLIC_IPFS_SECRET_API_KEY`

We are using the `xdv-universal-wallet-core` library which implements the `IPLDManager`, which instances an ipfs object
```javascript
import { IPLDManager } from 'xdv-universal-wallet-core';

const ipfs = new IPLDManager(did);
await ipfs.start(process.env.NEXT_PUBLIC_IPFS_URL);
```

I couldn't find any documentation for `xdv-universal-wallet-core` library in regards to passing in a bearer authentication or custom headers.

@mlopezdetrinidad , do you know how we could implement the changes?

### CODE REVIEW

**Comment by urbinaalex17** [comment]
@molekilla , we need your help with this. However, the blocker here is that [xdv-universal-wallet](https://www.npmjs.com/package/xdv-universal-wallet) does not implement any auth mechanism, so we need it to implement authentication using custom headers or authorization bearer with JWT in order to use an IPFS provider like Infura IPFS or Pinata Cloud.

**Comment by 92Sam** [comment]
I think this PR its deprecated, and @ryuheimat its working on this. 

@urbinaalex17 can you confirme this my friend?? 

thanks

**Comment by urbinaalex17** [comment]
> I think this PR its deprecated, and @ryuheimat its working on this.
> 
> @urbinaalex17 can you confirm this my friend??
> 
> thanks

Yes! I opened this PR a while back to make the changes in the xdv library. So if we won't use it anymore we can safely close this PR and redefined the [CH Story](https://app.clubhouse.io/masterventures/story/2041/as-a-frontend-engineer-i-need-to-modify-ipfs-endpoint-to-use-pinata-cloud-and-pass-in-authentication-headers). Thanks @92Sam !

**Comment by ryuheimat** [comment]
@92Sam I merged latest updates of `dev` branch to this branch, so i think we can continue with this PR.

**Pull request closed without merging**
